# Import Libraries

In [67]:
import pandas as pd
import numpy as np
print("Modual import successfully....")

Modual import successfully....

In [ ]:
path = 'data/imdb_top_movies_1980_2026.csv'

In [69]:
df = pd.read_csv(path)
df.head(10)

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
5,tt0109830,Forrest Gump,Forrest Gump,1994,142.0,"Drama,Romance",8.8,2492584,https://www.imdb.com/title/tt0109830
6,tt0110912,Pulp Fiction,Pulp Fiction,1994,154.0,"Crime,Drama",8.8,2431723,https://www.imdb.com/title/tt0110912
7,tt0133093,The Matrix,The Matrix,1999,136.0,"Action,Sci-Fi",8.7,2243917,https://www.imdb.com/title/tt0133093
8,tt0120737,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Fellowship of the Ring,2001,178.0,"Adventure,Drama,Fantasy",8.9,2203274,https://www.imdb.com/title/tt0120737
9,tt0167260,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King,2003,201.0,"Adventure,Drama,Fantasy",9.0,2161551,https://www.imdb.com/title/tt0167260

In [70]:
df.size
df.shape

(16252, 9)

In [71]:
df = df[['title', 'imdb_id', 'original_title', 'year', 'runtime_minutes', 'genres', 'average_rating', 'num_votes']]
df.head()

,title,imdb_id,original_title,year,runtime_minutes,genres,average_rating,num_votes
0,The Shawshank Redemption,tt0111161,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733
1,The Dark Knight,tt0468569,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984
2,Inception,tt1375666,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692
3,Fight Club,tt0137523,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984
4,Interstellar,tt0816692,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607

## Check null and duplicates

In [72]:
df.isnull().sum()

title              0
imdb_id            0
original_title     0
year               0
runtime_minutes    1
genres             6
average_rating     0
num_votes          0
dtype: int64

In [73]:
df.describe()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16252 entries, 0 to 16251
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            16252 non-null  str
 1   imdb_id          16252 non-null  str
 2   original_title   16252 non-null  str
 3   year             16252 non-null  int64
 4   runtime_minutes  16251 non-null  float64
 5   genres           16246 non-null  str
 6   average_rating   16252 non-null  float64
 7   num_votes        16252 non-null  int64
dtypes: float64(2), int64(2), str(4)
memory usage: 1.9 MB

In [74]:
df['runtime_minutes'] = df['runtime_minutes'].fillna(df['runtime_minutes'].mean())
df['runtime_minutes'].isnull().sum()
df.head()

,title,imdb_id,original_title,year,runtime_minutes,genres,average_rating,num_votes
0,The Shawshank Redemption,tt0111161,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733
1,The Dark Knight,tt0468569,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984
2,Inception,tt1375666,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692
3,Fight Club,tt0137523,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984
4,Interstellar,tt0816692,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607

In [75]:
df.isnull().sum()

title              0
imdb_id            0
original_title     0
year               0
runtime_minutes    0
genres             6
average_rating     0
num_votes          0
dtype: int64

In [76]:
# fill missing genres with 'Unknown' and verify
df['genres'] = df['genres'].fillna('Unknown')
df['genres'].isnull().sum()

np.int64(0)

In [77]:
df['genres'].value_counts()

genres
Comedy,Drama,Romance     760
Drama                    749
Comedy,Drama             686
Drama,Romance            535
Action,Crime,Drama       532
                        ...
Drama,Family,Horror        1
Animation,Family           1
Family,Fantasy             1
Comedy,Family,Western      1
Drama,Family,Music         1
Name: count, Length: 506, dtype: int64

# Cleaning

In [78]:
df['genres'] = df['genres'].str.lower()
df['title'] = df['title'].str.lower()
df['original_title'] = df['original_title'].str.lower()

In [79]:
df['imdb_id'] = df['imdb_id'].str.replace(r'^tt', '', regex=True)
df.head()

,title,imdb_id,original_title,year,runtime_minutes,genres,average_rating,num_votes
0,the shawshank redemption,0111161,the shawshank redemption,1994,142.0,drama,9.3,3182733
1,the dark knight,0468569,the dark knight,2008,152.0,"action,crime,drama",9.1,3161984
2,inception,1375666,inception,2010,148.0,"action,adventure,sci-fi",8.8,2811692
3,fight club,0137523,fight club,1999,139.0,"crime,drama,thriller",8.8,2601984
4,interstellar,0816692,interstellar,2014,169.0,"adventure,drama,sci-fi",8.7,2521607

In [ ]:
df.to_csv('data/cleaned-movie-data.csv')

In [81]:
pd.get_dummies(df)

,year,runtime_minutes,average_rating,num_votes,title_#alive,title_#home,title_#realityhigh,title_'71,title_'83,title_'round midnight,...,"genres_mystery,sci-fi,thriller","genres_mystery,thriller",genres_romance,"genres_romance,sci-fi","genres_romance,thriller","genres_romance,thriller,war",genres_sci-fi,"genres_sci-fi,thriller",genres_thriller,genres_unknown
0,1994,142.0,9.3,3182733,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2008,152.0,9.1,3161984,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2010,148.0,8.8,2811692,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1999,139.0,8.8,2601984,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2014,169.0,8.7,2521607,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16247,2016,127.0,6.7,5001,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16248,1991,154.0,7.2,5001,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16249,2020,98.0,5.3,5000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16250,1987,96.0,7.5,5000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16251,2010,120.0,6.4,5000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [82]:
len(df.loc[df['year'] == 2026, 'year'])

62

# Data Tranformation

In [83]:
df.head()

,title,imdb_id,original_title,year,runtime_minutes,genres,average_rating,num_votes
0,the shawshank redemption,0111161,the shawshank redemption,1994,142.0,drama,9.3,3182733
1,the dark knight,0468569,the dark knight,2008,152.0,"action,crime,drama",9.1,3161984
2,inception,1375666,inception,2010,148.0,"action,adventure,sci-fi",8.8,2811692
3,fight club,0137523,fight club,1999,139.0,"crime,drama,thriller",8.8,2601984
4,interstellar,0816692,interstellar,2014,169.0,"adventure,drama,sci-fi",8.7,2521607

In [84]:
def remove_space(text):
    return str(text).replace(" ", "")

In [85]:
def list_convert(text):
    return str(text).split(",")

In [86]:
df['title'] = df['title'].apply(remove_space)
df['genres'] = df['genres'].apply(remove_space)
df['original_title'] = df['original_title'].apply(remove_space)
df['genres'] = df['genres'].apply(list_convert)

In [87]:
import re

def clean_text_to_five(text):
    cleaned = re.sub(r'[^A-Za-z0-9\s]', '', str(text))
    words = cleaned.split()
    return words

In [88]:
df['genres'] = df['genres'].apply(clean_text_to_five)

In [89]:
def make_tags(row):
    genres = row['genres'] if isinstance(row['genres'], list) else [row['genres']]
    title = [str(row['title'])] if pd.notnull(row['title']) else []
    imdb_id = [str(row['imdb_id'])] if pd.notnull(row['imdb_id']) else []
    year = [str(int(row['year']))] if pd.notnull(row['year']) else []
    return title + genres + year + imdb_id 

df['tags'] = df.apply(make_tags, axis=1)

In [90]:
df2 = df[['imdb_id', 'title', 'tags']]
df2.head(10)

,imdb_id,title,tags
0,0111161,theshawshankredemption,"[theshawshankredemption, drama, 1994, 0111161]"
1,0468569,thedarkknight,"[thedarkknight, action, crime, drama, 2008, 04..."
2,1375666,inception,"[inception, action, adventure, scifi, 2010, 13..."
3,0137523,fightclub,"[fightclub, crime, drama, thriller, 1999, 0137..."
4,0816692,interstellar,"[interstellar, adventure, drama, scifi, 2014, ..."
5,0109830,forrestgump,"[forrestgump, drama, romance, 1994, 0109830]"
6,0110912,pulpfiction,"[pulpfiction, crime, drama, 1994, 0110912]"
7,0133093,thematrix,"[thematrix, action, scifi, 1999, 0133093]"
8,0120737,thelordoftherings:thefellowshipofthering,"[thelordoftherings:thefellowshipofthering, adv..."
9,0167260,thelordoftherings:thereturnoftheking,"[thelordoftherings:thereturnoftheking, adventu..."

In [91]:
df2['tags'] = df2['tags'].apply(lambda x:" ".join(x))

In [92]:
df2.head(10)

,imdb_id,title,tags
0,0111161,theshawshankredemption,theshawshankredemption drama 1994 0111161
1,0468569,thedarkknight,thedarkknight action crime drama 2008 0468569
2,1375666,inception,inception action adventure scifi 2010 1375666
3,0137523,fightclub,fightclub crime drama thriller 1999 0137523
4,0816692,interstellar,interstellar adventure drama scifi 2014 0816692
5,0109830,forrestgump,forrestgump drama romance 1994 0109830
6,0110912,pulpfiction,pulpfiction crime drama 1994 0110912
7,0133093,thematrix,thematrix action scifi 1999 0133093
8,0120737,thelordoftherings:thefellowshipofthering,thelordoftherings:thefellowshipofthering adven...
9,0167260,thelordoftherings:thereturnoftheking,thelordoftherings:thereturnoftheking adventure...

In [ ]:
df2.to_csv("data/preproccess_data.csv")